export type DataRow = {
    date: number,
    lastUpdated: string,
    death: number,
    deathIncrease: number,
    hospitalizedCumulative: number,
    hospitalizedCurrently: number,
    hospitalizedIncrease: number,
    inIcuCumulative: number,
    inIcuCurrently: number,
    negative: number,
    pending: number,
    positive: number,
    posNeg: number,
    totalTests: number,
    percentPositive: number,
    negativeIncrease: number,
    positiveIncrease: number,
    totalTestsIncrease: number,
    recovered: number,
}