name: Combine Federal Data
on: 
  schedule:
    - cron: '20 * * * *'
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  combine-data:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'All credit to the COVID Tracking Project'
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Make sure data dir exists
        run: mkdir -p data
      - name: Run combiner
        run: deno run combine-data.ts
      - name: Commit
        if: github.ref == 'refs/heads/master'
        uses: EndBug/add-and-commit@v7
        with:
          message: Updating combined federal data
          add: 'data'
          default_author: github_actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}